[Devops][g11n-csharp-client] Add smoke test job to CI
vmware/singleton pull request #1126
Opened 2021-05-25 08:57 UTC by WisdomLuo

Add smoke test to CI pipeline

2021-05-25 09:02 UTC, surite requested changes

2021-05-25 09:02 UTC, surite commented on .travis.yml
> +        - true
suggest to comment whole UT stage to skip it, leave a blank true result will confuse people if we have executed UT.

2021-05-25 09:27 UTC, surite approved these changes

2021-05-26 06:02 UTC, junw-33455432 approved these changes

2021-05-26 06:04 UTC, merged