upload the smoke test code of ruby client
vmware/singleton pull request #1421
Opened 2022-01-06 01:19 UTC by dleng-vmware

2022-01-11 08:42 UTC, lyiyu66 approved these changes

2022-01-11 08:45 UTC, surite requested changes
please remove all .DS_Store files

2022-01-11 13:20 UTC, dleng-vmware commented
ok, all .DS_Store files are removed

2022-01-12 01:37 UTC, lyiyu66 approved these changes

2022-01-12 02:06 UTC, surite approved these changes
it is better to separate test verification data from code, for example https://github.com/vmware/singleton/pull/1421/files#diff-a5b09f544c635b592c2685d4580496a5af8041e85e14723d272c4c1ffe8cf0d1R31

2022-01-12 06:23 UTC, closed without merging