[Ruby client] add validation to nil parameter
vmware/singleton pull request #1487
Opened 2022-02-09 08:41 UTC by linr211

Changes of this PR:
1. Add validation to nil locale parameter in the API
2. fix issue https://github.com/vmware/singleton/issues/1479
3. fix issue https://github.com/vmware/singleton/issues/1484
4. Change default_language to source_locale
5. Change to log level to debug when the key is missed

2022-02-09 16:55 UTC, jessiejuachon submitted a review, later dismissed

2022-02-10 01:58 UTC, linr211 commented on lib/sgtn-client/api/source.rb
> +          SgtnClient.logger.error "[Source][loadBundles]the input is nil!"
fixed.

2022-02-10 02:27 UTC, Xiaochao8 commented
I wonder what's the reason to 'Change default_language to source_locale'?

2022-02-10 04:01 UTC, linr211 commented
> I wonder what's the reason to 'Change default_language to source_locale'?

Jessie mentioned it in a email thread:
1. We should use “source” instead of “default” because we actually mean the source or origin of translation.
2. We should use “locale” instead of “language”. Technically, a locale (or language tag) can be composed of many subtags: language-extlang-script-region-variant-extension-privateuse. At the minimum, a locale may contain only the language subtag (e.g. “en”). In our case,  the source locale is actually en-US (i.e. language-region).

2022-02-10 17:10 UTC, jessiejuachon commented on lib/sgtn-client/api/translation.rb
> +            SgtnClient.logger.debug "[Translation][getString]can't find key=#{key}, component=#{component}, locale=#{locale}!!!"
This is for a different, higher-priority issue: https://github.com/vmware/singleton/issues/1493
Next time, please keep the PR as small as possible.

2022-02-10 17:10 UTC, jessiejuachon commented on lib/sgtn-client/api/translation.rb
> +            SgtnClient.logger.debug "[Translation][getString_p]can't find key=#{key}, component=#{component}, locale=#{locale}!!!"
This is for a different, higher-priority issue: https://github.com/vmware/singleton/issues/1493
Next time, please keep the PR as small as possible.

2022-02-10 17:11 UTC, jessiejuachon commented on lib/sgtn-client/api/translation.rb
> +            SgtnClient.logger.debug "[Translation][getStrings]can't find component=#{component}, locale=#{locale}!!!"
This is for a different, higher-priority issue: https://github.com/vmware/singleton/issues/1493
Next time, please keep the PR as small as possible.

2022-02-10 17:16 UTC, jessiejuachon requested changes

2022-02-10 17:16 UTC, jessiejuachon commented on lib/sgtn-client/util/locale-util.rb
> +            parts = locale.to_s.split("-")
This is for a different issue: https://github.com/vmware/singleton/issues/1479
Please move to a different PR.

2022-02-10 17:16 UTC, jessiejuachon commented on lib/sgtn-client/util/cache-util.rb
> +        return product_name + "_" + version + "_" + component + "_" + lc.to_s
This is for a different issue: https://github.com/vmware/singleton/issues/1479
Please move to a different PR.

2022-02-10 17:18 UTC, jessiejuachon commented
I realize some code that are unrelated might cause an issue separately. Also, some code fixes are higher priority, so requesting to break this into smaller PRs and link to appropriate issues logged.

2022-02-10 21:11 UTC, jessiejuachon requested changes

2022-02-11 00:06 UTC, jessiejuachon commented on lib/sgtn-client/api/source.rb
> +        if locale.nil?
Do not hide the exception here as nil calue for locale is invalid for this API method.

2022-02-11 00:13 UTC, closed without merging

2022-02-11 08:43 UTC, linr211 commented
> 

sure