upgrade the snakeyaml jar
vmware/singleton pull request #1874
Opened 2022-09-07 06:28 UTC by tigershi

2022-09-07 07:03 UTC, Xiaochao8 approved these changes

2022-09-20 06:48 UTC, huihuiw01 requested changes

2022-09-20 06:48 UTC, huihuiw01 commented on g11n-ws/build.gradle
> +    	snakeyam="1.31"
I check maven repo today, the latest version is 1.32, please change it to the latest.

2022-09-20 07:03 UTC, huihuiw01 approved these changes

2022-09-20 07:04 UTC, Xiaochao8 approved these changes

2022-09-20 07:34 UTC, merged