upgrade yaml
vmware/singleton pull request #1965
Opened 2022-11-24 08:00 UTC by tigershi

2022-11-24 09:36 UTC, Xiaochao8 approved these changes

2022-11-25 06:24 UTC, linr211 approved these changes

2022-11-29 02:36 UTC, Xiaochao8 requested changes
Please update subject because not only YAML is updated.

2022-11-29 02:46 UTC, Xiaochao8 approved these changes

2022-11-29 02:54 UTC, huihuiw01 approved these changes

2022-11-29 03:27 UTC, merged