add the 说
vmware/singleton pull request #950
Opened 2021-01-11 06:25 UTC by tigershi

2021-01-11 08:36 UTC, Xiaochao8 commented
Could you connect the issue?

2021-01-14 13:22 UTC, linr211 approved these changes

2021-01-15 09:35 UTC, Xiaochao8 requested changes

2021-01-15 10:06 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
> +		basePath = basePath.replace(ConstantsChar.DOT, "").replace(ConstantsChar.BACKSLASH, "");
The replace method only replace the first '/' and '.'

2021-01-15 10:07 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/test/java/com/vmware/test/TestModels.java
> +    	String data = "Jfe9vTfTsU6OQfZ4xikT+oKxytZOB1binD5wi10n2GMoI+4Jc/Yyy9x9WbTbzj1a4lM6nGBYnOQSjFn3e1QhcL8uj7eCg9mLt6bTec1FGi5ctPFrJexnkBX9lis+qQ1ntwkbf6h2g6U1SYN7N/t+/fq7ubybR6QdKY6hNwIJrCA=";
Not, this is a test code

2021-01-15 10:15 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/source/dao/impl/S3SourceDaoImpl.java
> +	    req.setPrefix(prefix.toString());
I agree with you. Colin suggest can't have a blank line in method that we discuss in code format meeting

2021-01-15 10:23 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/conf/PropertyConfigs.java
> +		} catch (ParseException e) {
I don't agree with you. Because return 0 that means throw exception

2021-01-15 10:31 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/conf/PropertyConfigs.java
> +			result =1;
Because you can't make sure result ==1 when it has exception happen

2021-01-15 10:36 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordServiceImpl.java
>  	public List<RecordModel> getRecordModelsByRemote() {
this is not deprecated

2021-01-15 10:40 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordServiceImpl.java
> +		    		rm.setStatus(0);
It is need use the status when send the content. I have explained detailed in previous PR

2021-01-15 10:45 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +	    logger.info(basePath);
done

2021-01-15 10:47 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +			if(configs.getRecordApiVersion().equalsIgnoreCase("s3")) {
Because the all configuration in PropertyConfigs  Object

2021-01-15 10:52 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/RecordService.java
> +	public boolean synchRecordModelsByRemote(RecordModel record);
Not  deprecate

2021-01-15 10:54 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +	    	   syncResource(record);
Because it has duplicate data， need to reduce the duplicate data first.

2021-01-15 10:55 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +				logger.error("write local ComponentSourceModel error! record-{}-{}-{}-{}",record.getProduct(), record.getVersion(), record.getComponent());
done

2021-01-15 10:58 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +					lastModifyTime = rm.getStatus();
Not, The next time will change the query parameter lastModifyTime  when get update records

2021-01-15 10:59 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +	    	 rm.setStatus(0);
It is necessary, It need record the time when send to i18n.

2021-01-15 11:03 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/schedule/SourceRequestCron.java
> +		logger.error("Not find sync s3 list file!");
return null has same mean when throw exception

2021-01-15 11:05 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentServiceImpl.java
> +			    	result = synchkey2VipI18n(record, entry.getKey(), (String)entry.getValue(), null, null);
yes.

2021-01-15 11:05 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/java/com/vmware/l10agent/service/SingleComponentServiceImpl.java
> +			    			if(record.getStatus()<5) {
commit 5 time when commit error

2021-01-15 11:06 UTC, tigershi commented on g11n-ws/vip-manager-l10n-agent/src/main/resources/application.properties
> +vip.l10n.base.url=https://localhost:8088
one is remote l10n, other is internal l10n

2021-01-15 11:08 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
> +			String record = request.getParameter("recordUpdate");
The parameter is mean last query time, only sync update data.

2021-01-15 11:13 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
> +		if ((recordList != null) && (recordList.size() > 0)) {
Remove recordList != null have null pointer exception

2021-01-15 11:27 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
> +			logger.warn("parse lastModify error: {}", longDate);
this is configurate by user

2021-01-15 11:29 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
> +			@RequestParam(value =APIParamName.LONGDATE, required=false)String longDate, HttpServletRequest request) throws L10nAPIException{
yes, It have configuration in l10n agent

2021-01-15 11:36 UTC, tigershi commented on g11n-ws/vip-manager-l10n/src/main/java/com/vmware/l10n/record/controller/RecordController.java
> +			lastModifyTime = 0;
done

2021-01-18 04:26 UTC, linr211 submitted a review, later dismissed

2021-01-19 09:59 UTC, Xiaochao8 approved these changes

2021-01-20 04:18 UTC, linr211 approved these changes

2021-01-20 05:52 UTC, merged