[service] upgrade singleton service dependency jars
vmware/singleton pull request #952
Opened 2021-01-11 07:23 UTC by tigershi

2021-01-11 07:25 UTC, Xiaochao8 approved these changes

2021-01-11 07:45 UTC, Xiaochao8 reviewed
Could you connect the issue?

2021-01-12 12:59 UTC, linr211 approved these changes

2021-01-13 09:39 UTC, linr211 approved these changes

2021-01-14 02:44 UTC, Xiaochao8 requested changes
Could you connect the issue?

2021-01-14 06:09 UTC, huihuiw01 approved these changes

2021-01-14 06:58 UTC, Xiaochao8 approved these changes

2021-01-14 07:08 UTC, merged