[g11n-cldr-pattern]fixed the scan bugs
vmware/singleton pull request #959
Opened 2021-01-13 10:26 UTC by tigershi

2021-01-14 03:06 UTC, Xiaochao8 requested changes
Please connect the issue.

2021-01-14 03:30 UTC, Xiaochao8 commented on src/main/java/com/vmware/i18n/cldr/CLDR.java
> +    private String regex = "(([a-z]{2,3})(-([A-Z][a-z]{3}))?(-([A-Z]{2}|[0-9]{3}))?)((-([a-zA-Z0-9]{5,8}|[0-9][a-zA-Z0-9]{3}))*)|(root)";
Please correct the format to align with the file.

2021-01-14 04:11 UTC, Xiaochao8 commented on src/main/java/com/vmware/i18n/utils/LocaleDataUtils.java
> +}
Add a new line at the end of file.

2021-01-14 12:42 UTC, linr211 approved these changes

2021-01-15 01:07 UTC, Xiaochao8 approved these changes

2021-01-15 06:40 UTC, merged